#!/bin/bash
DATE=$(date +%F)
SCRIPT_NAME=$0
LOGDIR=/tmp
LOGFILE=$LOGDIR/$DATE-$SCRIPT_NAME
R="/e[31m"
G="/e[32m]"
USERID=$(id -u)
if [ $USERID -ne 0 ];
then
   echo "user must have root access"
   exit 1
fi

VALIDATE(){
   if [ $1 -ne 0 ];
   then 
      echo -e "$2 $R is failure $R"
      exit 1
   else 
      echo "$2 is $G success $G"
    fi
}



yum install nodejs -y
VALIDATE $? "nodejs is installed"


mkdir /app
VALIDATE $? "dir got created"

curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
VALIDATE $? "catalogue packge download"

cd /app
VALIDATE "change dir to app"

unzip /tmp/catalogue.zip
